import { CardInterface, COURSE_LVL } from "./primeInterface";

export const CardData: CardInterface[] = [
  {
    heading: "Angular RXJS",
    subheading: "Reactive Programming with Observables",
    description:
      "RxJS (Reactive Extensions for JavaScript) is a library for reactive programming using observables. It allows handling asynchronous events with powerful operators. In Angular, RxJS is commonly used for HTTP requests and event handling. It enables efficient data streams and complex state management.",
    courseLevel: COURSE_LVL.ADVANCED,
    requiredExperience: 3,
    duration: "8 hours",
    instructor: "John Doe",
    rating: 4.5,
    reviewsCount: 120,
    price: 49.99,
    tags: ["RxJS", "Reactive Programming", "Observables"],
    thumbnailUrl: "https://example.com/rxjs-thumbnail.jpg",
    syllabus: ["Introduction to Observables", "Operators", "Subjects", "Error Handling"],
    isCertified: true,
    enrollmentCount: 500,
  },
  {
    heading: "Angular Dependency Injection",
    subheading: "Managing Dependencies Effectively",
    description:
      "Dependency Injection (DI) in Angular is a design pattern for managing class dependencies. It allows components to request services instead of creating them manually. This promotes modularity, better testing, and code maintainability. Angular's DI framework uses providers to inject dependencies.",
    courseLevel: COURSE_LVL.ADVANCED,
    requiredExperience: 3,
    duration: "6 hours",
    instructor: "Jane Smith",
    rating: 4.7,
    reviewsCount: 90,
    price: "Free",
    tags: ["Dependency Injection", "Angular Services", "Providers"],
    thumbnailUrl: "https://example.com/di-thumbnail.jpg",
    syllabus: ["Introduction to DI", "Providers and Tokens", "Hierarchical DI"],
    isCertified: true,
    enrollmentCount: 800,
  },
  {
    heading: "Angular Lifecycle Hooks",
    subheading: "Understanding Component Lifecycle",
    description:
      "Lifecycle hooks in Angular are methods that get called at specific stages of a component's lifecycle. Key hooks include OnInit, OnChanges, and OnDestroy. They provide control over initialization, change detection, and cleanup. These hooks enhance component behavior and resource management.",
    courseLevel: COURSE_LVL.EXPERT,
    requiredExperience: 5,
    duration: "5 hours",
    instructor: "Michael Johnson",
    rating: 4.6,
    reviewsCount: 75,
    price: 29.99,
    tags: ["Lifecycle Hooks", "Angular Components"],
    thumbnailUrl: "https://example.com/lifecycle-thumbnail.jpg",
    syllabus: ["OnInit", "OnChanges", "OnDestroy", "Other Hooks"],
    isCertified: true,
    enrollmentCount: 400,
  },
  {
    heading: "Angular Forms",
    subheading: "Handling User Inputs and Validation",
    description:
      "Angular provides two approaches for handling forms: Template-driven and Reactive forms. Template-driven forms are simple and declarative, while Reactive forms offer greater control and flexibility. Both approaches support form validation, user input handling, and data binding efficiently.",
    courseLevel: COURSE_LVL.BEGINNER,
    requiredExperience: 1,
    duration: "7 hours",
    instructor: "Alice Brown",
    rating: 4.8,
    reviewsCount: 150,
    price: 39.99,
    tags: ["Forms", "Validation", "Reactive Forms"],
    thumbnailUrl: "https://example.com/forms-thumbnail.jpg",
    syllabus: ["Template-driven Forms", "Reactive Forms", "Validation"],
    isCertified: true,
    enrollmentCount: 600,
  },
  {
    heading: "Angular Routing",
    subheading: "Navigating Between Views",
    description:
      "Angular's Router module enables navigation between different views or pages. It supports route parameters, lazy loading, and guards for securing routes. Router configuration is done using the Routes array. This system allows building single-page applications with multiple views seamlessly.",
    courseLevel: COURSE_LVL.ADVANCED,
    requiredExperience: 3,
    duration: "9 hours",
    instructor: "David Wilson",
    rating: 4.7,
    reviewsCount: 200,
    price: "Free",
    tags: ["Routing", "Lazy Loading", "Guards"],
    thumbnailUrl: "https://example.com/routing-thumbnail.jpg",
    syllabus: ["Route Configuration", "Route Guards", "Lazy Loading"],
    isCertified: true,
    enrollmentCount: 700,
  },
  {
    heading: "Node.js Performance Optimization",
    subheading: "Improve Node.js Application Speed",
    description:
      "Learn how to optimize Node.js applications for better performance. Topics include event loop optimization, memory management, and using tools like PM2 and clustering.",
    courseLevel: COURSE_LVL.EXPERT,
    requiredExperience: 5,
    duration: "10 hours",
    instructor: "Emily White",
    rating: 4.9,
    reviewsCount: 250,
    price: 59.99,
    tags: ["Node.js", "Performance", "Optimization"],
    thumbnailUrl: "https://example.com/nodejs-performance-thumbnail.jpg",
    syllabus: ["Event Loop", "Memory Management", "PM2 & Clustering"],
    isCertified: true,
    enrollmentCount: 900,
  },
  {
    heading: "MongoDB Aggregation Framework",
    subheading: "Master MongoDB Aggregation Pipelines",
    description:
      "Learn how to use MongoDB's powerful aggregation framework to process and transform data efficiently. Covers stages like $match, $group, and $lookup.",
    courseLevel: COURSE_LVL.ADVANCED,
    requiredExperience: 3,
    duration: "8 hours",
    instructor: "Sophia Miller",
    rating: 4.8,
    reviewsCount: 180,
    price: 45.99,
    tags: ["MongoDB", "Aggregation", "Database"],
    thumbnailUrl: "https://example.com/mongodb-aggregation-thumbnail.jpg",
    syllabus: ["Aggregation Basics", "$match", "$group", "$lookup"],
    isCertified: true,
    enrollmentCount: 850,
  },
  {
    heading: "Advanced JavaScript Patterns",
    subheading: "Enhance Your JavaScript Skills",
    description:
      "Dive into advanced JavaScript patterns like Module, Factory, Observer, and Singleton. Understand closures, prototypal inheritance, and performance optimizations.",
    courseLevel: COURSE_LVL.EXPERT,
    requiredExperience: 5,
    duration: "12 hours",
    instructor: "Daniel Brown",
    rating: 4.9,
    reviewsCount: 300,
    price: 69.99,
    tags: ["JavaScript", "Patterns", "Advanced"],
    thumbnailUrl: "https://example.com/js-patterns-thumbnail.jpg",
    syllabus: ["Module Pattern", "Factory Pattern", "Observer Pattern"],
    isCertified: true,
    enrollmentCount: 1100,
  },
  {
    heading: "React Performance Optimization",
    subheading: "Improve Your React Apps",
    description:
      "Optimize React applications with techniques like memoization, useMemo, useCallback, and React Profiler. Improve rendering efficiency and reduce re-renders.",
    courseLevel: COURSE_LVL.BEGINNER,
    requiredExperience: 1,
    duration: "9 hours",
    instructor: "Olivia Clark",
    rating: 4.8,
    reviewsCount: 220,
    price: 55.99,
    tags: ["React", "Performance", "Optimization"],
    thumbnailUrl: "https://example.com/react-performance-thumbnail.jpg",
    syllabus: ["Memoization", "React Profiler", "Reducing Re-renders"],
    isCertified: true,
    enrollmentCount: 950,
  },
  {
    heading: "REST API Design Best Practices",
    subheading: "Build Scalable REST APIs",
    description:
      "Learn how to design scalable and maintainable RESTful APIs. Covers versioning, authentication, rate limiting, and proper status codes usage.",
    courseLevel: COURSE_LVL.BEGINNER,
    requiredExperience: 1,
    duration: "6 hours",
    instructor: "William Johnson",
    rating: 4.6,
    reviewsCount: 100,
    price: 39.99,
    tags: ["REST API", "Best Practices", "Backend"],
    thumbnailUrl: "https://example.com/rest-api-thumbnail.jpg",
    syllabus: ["Versioning", "Authentication", "Rate Limiting"],
    isCertified: true,
    enrollmentCount: 750,
  },
];
